name = "clipboard"
compatibility_date = "2026-04-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "clipboard-db"
database_id = "dcc9e811-edfe-46bd-a16f-1790ce48eb39"
